apiVersion: apps/v1
kind: Replication
metadata:
  name: rahulgandhale-myweb2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
    rahulgandhale: myweb2
  template:
    metadata:
      labels:
        rahulgandhale: myweb2
    spec:
      containers:
      - name:  rahulgandhale-myweb2
        image: rahulgandhale/myweb2
---
apiVersion: v1
kind: Service
metadata:
  name: myweb2-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
   rahulgandhale: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8002
